/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sonalake.shotgun;

import com.sonalake.shotgun.cli.Params;
import com.sonalake.shotgun.usage.ShotgunConfig;
import com.sonalake.shotgun.usage.ShotgunModel;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.Task;

import static org.apache.commons.lang3.StringUtils.isBlank;


/**
 * A simple 'hello world' plugin.
 */
public class ShotgunGradlePluginPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        Params params = project.getExtensions().create("shotgun", Params.class);
        project.getTasks().register("analyse", task -> {
            task.doLast(s -> analyse(s, params));
        });
    }

    private void analyse(Task task, Params params) {
        if (isBlank(params.getInputDirectory()))  {
            params.setInputDirectory(".");
        }

        ShotgunConfig config = params.toConfig();
        App shotgun = new App();
        ShotgunModel model = shotgun.analyseGit(config);
        shotgun.writeReport(config, model);


    }
}
