/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sonalake.shotgun;

import com.sonalake.shotgun.cli.Params;
import com.sonalake.shotgun.usage.ShotgunConfig;
import com.sonalake.shotgun.usage.ShotgunModel;
import org.gradle.api.Plugin;
import org.gradle.api.Project;

import static org.apache.commons.lang3.StringUtils.isBlank;


public class ShotgunGradlePlugin implements Plugin<Project> {
  public void apply(Project project) {
    // Register a task
    Params params = project.getExtensions().create("shotgun", Params.class);

    if (isBlank(params.getInputDirectory())) {
      String localProjectDir = project.getProjectDir().toPath().toAbsolutePath().toString();
      params.setInputDirectory(localProjectDir);
    }

    project.getTasks()
      .register("shotgun",
        task -> task.doLast(s -> analyse(params))
      );
  }

  void analyse(Params params) {
    ShotgunConfig config = params.toConfig();
    App shotgun = new App();
    ShotgunModel model = shotgun.analyseGit(config);
    shotgun.writeReport(config, model);
    System.out.println("Report written to " + params.getOutputFile());

  }
}
