/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sonalake.shotgun;

import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.Test;

import static org.junit.Assert.assertNotNull;

/**
 * A simple unit test for the 'com.sonalake.shotgun.greeting' plugin.
 */
public class ShotgunGradlePluginPluginTest {
    @Test
    public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("com.sonalake.shotgun");

        // Verify the result
        assertNotNull(project.getTasks().findByName("analyse"));
    }
}
