/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sonalake.shotgun;

import com.sonalake.shotgun.cli.Params;
import org.gradle.api.Action;
import org.gradle.api.Project;
import org.gradle.api.Task;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * A simple unit test for the 'com.sonalake.shotgun.greeting' plugin.
 */
public class ShotgunGradlePluginTest {
  @Test
  public void pluginRegistersATask() throws IOException {
    // build a project
    Project project = ProjectBuilder.builder().build();

    // apply the plugin
    project.getPlugins().apply("shotgun-gradle-plugin");

    // now configure this
    String here = Path.of(".").toAbsolutePath().toString();
    String there = Files.createTempFile("shotgun.", ".html").toAbsolutePath().toString();
    project.getExtensions().configure("shotgun",
      (Action<Params>) params -> {
        params.setInputDirectory(here);
        params.setOutputFile(there);
      }
    );

    // assert the task exists
    Task task = project.getTasks().findByName("shotgun");
    assertNotNull("No shotgun task created", task);

    // run the task
    task.getActions().get(0).execute(null);

    // check we got an output file
    assertTrue("No output file found", Files.exists(Path.of(there)));


  }

}
